seed_everything: 123
trainer:
  max_epochs: 5
  callbacks+:
    - class_path: src.callbacks.Evaluator
model:
  class_path: src.models.UniBlocker
  init_args:
    model_name_or_path: "./models/all-mpnet-base-v2"
    max_length: 256
    augment_prob: 0.01
    hidden_dropout_prob: 0.15
    pooler_type: average
    m: 0.4
    gamma: 80
    learning_rate: 1.0e-05
    distance: 0.8
    adam_epsilon: 1.0e-08
    warmup_steps: 0
    weight_decay: 0.0
    scheduler_type: linear
